#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Twist

def talker():
	pub = rospy.Publisher('/turtle1/cmd_vel', Twist, queue_size=10)
	rospy.init_node('my_teleop_node', anonymous=True)
	rate = rospy.Rate(10)

	while not rospy.is_shutdown():
		move_cmd = Twist()
		# Linear speed in x in units/second: positive values imply # forward, negative values == backwards
		move_cmd.linear.x = 0
		# Turn at 0.5 radians/s move_cmd.angular.z = 0.5 rotation
		move_cmd.angular.z = 0

		value = raw_input()
		#getch.__init__()
		#value = getch.__call__()
		if(value == 'w' or value == 'W'):
			move_cmd.linear.x = 1
		if(value == 's' or value == 'S'):
			move_cmd.linear.x = -0.5
		if(value == 'a' or value == 'A'):
			move_cmd.angular.z = 1
		if(value == 'd' or value == 'D'):
			move_cmd.angular.z = -0.5
			
		rospy.loginfo(move_cmd)
		pub.publish(move_cmd)
		rate.sleep()

if __name__ == '__main__':
	try:
		talker()
	except rospy.ROSInterruptException:
		pass